import { useState, useEffect } from 'react'

// Dummy VAPID public key for testing (you should replace this with a real one generated by your backend)
// This is required to subscribe to push notifications
const VAPID_PUBLIC_KEY = 'BEl62iUYgUivxIkv69yViEuiBIa-Ib9-SkvMeAtA3LFgDzkrxZJjSgSnfckjBJuBkr3qBUYIHBQFLXYp5Nksh8U'

export function usePushNotifications() {
  const [isSupported, setIsSupported] = useState(false)
  const [permission, setPermission] = useState(null)
  const [subscription, setSubscription] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)

  useEffect(() => {
    // Check if service workers and push messaging are supported
    const supported = 'serviceWorker' in navigator && 'PushManager' in window
    setIsSupported(supported)
    
    if (supported) {
      // Check current permission status
      setPermission(Notification.permission)
      
      // Check for existing subscription
      navigator.serviceWorker.ready.then((registration) => {
        registration.pushManager.getSubscription().then((sub) => {
          setSubscription(sub)
        })
      })
    }
  }, [])

  // Helper function to convert base64 to Uint8Array required for push subscriptions
  const urlBase64ToUint8Array = (base64String) => {
    const padding = '='.repeat((4 - base64String.length % 4) % 4)
    const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/')
    
    const rawData = window.atob(base64)
    const outputArray = new Uint8Array(rawData.length)
    
    for (let i = 0; i < rawData.length; ++i) {
      outputArray[i] = rawData.charCodeAt(i)
    }
    return outputArray
  }

  const requestPermission = async () => {
    if (!isSupported) {
      setError('Push notifications are not supported in this browser.')
      return
    }

    setLoading(true)
    setError(null)

    try {
      const result = await Notification.requestPermission()
      setPermission(result)
      
      if (result === 'granted') {
        await subscribeToPush()
      } else {
        setError('Permission denied for push notifications.')
      }
    } catch (err) {
      setError('Failed to request permission: ' + err.message)
    } finally {
      setLoading(false)
    }
  }

  const subscribeToPush = async () => {
    if (!isSupported || permission !== 'granted') return

    setLoading(true)
    setError(null)

    try {
      const registration = await navigator.serviceWorker.ready
      
      // Only subscribe if not already subscribed
      let sub = await registration.pushManager.getSubscription()
      if (!sub) {
        sub = await registration.pushManager.subscribe({
          userVisibleOnly: true,
          applicationServerKey: urlBase64ToUint8Array(VAPID_PUBLIC_KEY)
        })
        setSubscription(sub)
      }
      
      console.log('Push subscription successful:', sub)
      // TODO: Send `sub` to your backend server to save it
      
    } catch (err) {
      console.error('Failed to subscribe:', err)
      setError('Failed to subscribe to push notifications: ' + err.message)
    } finally {
      setLoading(false)
    }
  }

  const unsubscribeFromPush = async () => {
    if (!subscription) return

    setLoading(true)
    setError(null)

    try {
      const successful = await subscription.unsubscribe()
      if (successful) {
        setSubscription(null)
        console.log('Unsubscribed from push notifications')
        // TODO: Tell your backend to remove this subscription
      }
    } catch (err) {
      console.error('Failed to unsubscribe:', err)
      setError('Failed to unsubscribe from push notifications: ' + err.message)
    } finally {
      setLoading(false)
    }
  }

  return {
    isSupported,
    permission,
    subscription,
    loading,
    error,
    requestPermission,
    unsubscribeFromPush
  }
}
